name: clientServerApp

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup clientServerApp
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Restore dependencies
      run: appCS restore
    - name: Build
      run: appCS build --no-restore
    #- name: Run tests
      #run: appCS test --no-build --verbosity normal
